# This is a basic workflow to help you get started with Actions

name: Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_and_test"
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            ~/.local
          key: ${{ runner.os }}-deps

      - name: Install prerequisites
        run: ./misc/install-deps-linux-x64.sh

      - name: Compile Haskell dependencies
        run: |
          export PATH=$HOME/.local/bin:$PATH
          stack --no-terminal test --only-dependencies

      - name: Compile and test
        run: |
          export PATH=$HOME/.local/bin:$PATH
          stack --no-terminal test
